/* This file is generated by Blueprint_C */ 

class UUMG_AiAgent_C : public UUserWidget 
{
public:
    static UClass* StaticClass()
    {
        return LoadObject<UClass>(nullptr, TEXT("/Game/UI/View/AiAgent/UMG_AiAgent.UMG_AiAgent_C")); 
    }

    UPROPERTY(BlueprintReadOnly, Instanced, NotReplicated, Meta = (EditInline="true", DisplayName="Button_Ask", Category="UMG_AiAgent"))
    TObjectPtr<UButton> Button_Ask;

    UPROPERTY(BlueprintReadOnly, Instanced, NotReplicated, Meta = (EditInline="true", DisplayName="Text_Content", Category="UMG_AiAgent"))
    TObjectPtr<UMultiLineEditableText> Text_Content;


};