/* This file is generated by Blueprint_C */ 

class UView_AiAgent_C : public UUserWidget 
{
public:
    static UClass* StaticClass()
    {
        return LoadObject<UClass>(nullptr, TEXT("/Game/UI/View/AiAgent/View_AiAgent.View_AiAgent_C")); 
    }


};