/* This file is generated by Blueprint_C */ 

class UUMG_GroupHeader_C : public UUserWidget 
{
public:
    static UClass* StaticClass()
    {
        return LoadObject<UClass>(nullptr, TEXT("/Game/UI/View/Basic/Settings/Item/UMG_GroupHeader.UMG_GroupHeader_C")); 
    }

    UPROPERTY(BlueprintReadOnly, Instanced, NotReplicated, Meta = (EditInline="true", DisplayName="Name", Category="UMG_GroupHeader"))
    TObjectPtr<UTextBlock> Name;


};